service: vanity-number-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TableName: VanityNumbers
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
functions:
  generateVanityNumbers:
    handler: index.handler
    events:
      - http:
          path: generate
          method: post

resources:
  Resources:
    VanityNumbersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VanityNumbers
        AttributeDefinitions:
          - AttributeName: PhoneNumber
            AttributeType: S
        KeySchema:
          - AttributeName: PhoneNumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dynamodb-local
  - serverless-offline
